### ISSUE TITLE
Health table 2a

### ISSUE THREAD

**Issue by weikang9009** [AnGWar26/icsd-pulse#1]
Notice that the source of income (e.g., Borrowing from friends or family) was recently added to the questionable and to the detailed tables (starting from week 7). If you look at [week 6's table](https://www2.census.gov/programs-surveys/demo/tables/hhp/2020/wk6/health2a_week6.xlsx), these rows do not exist. So we might need to think about more generic socioeconomic characteristics (e.g., education attainment/age) to look at in addition to whether the households have borrowed money from others.

**Comment by AnGWar26** [comment]
Hello Wei,

This is a good catch. This applies to my first question about food insecurity, and I have modified the README to show my new question selection. I have also added the question I seek to answer regarding employment, which I forgot to push before.

Thanks!

**Comment by weikang9009** [comment]
Thanks! We might want to define the questions more specifically (divide and conquer). But I am sure you are doing that! Looking forward to the meeting tomorrow. 

If you want, you can create an issue for each dimension (topic). It might make it easier to add thoughts and questions specific to the topic.
